backend:
  name: github
  repo: hansdiepstraten/fingerpoppin-soul
  branch: master
  base_url: https://sveltia-cms-auth.sherryb.workers.dev

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: blog
    label: Blog
    label_singular: Blog post
    folder: src/content/blog
    create: true
    delete: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - label: Category
        name: category
        widget: select
        options: [Announcements, Show, Hideaway]
        default: Announcements
      - { label: Image, name: image, widget: image, required: false }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }
